apiVersion: v1
kind: Service
metadata:
  name: {{ include "elisa.fullname" . }}-db
  labels:
    {{- include "elisa_db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.elisa_db.service.type }}
  ports:
    - port: {{ .Values.elisa_db.service.port }}
      targetPort: {{ .Values.elisa_db.service.port }}
      protocol: TCP
      name: {{ include "elisa.fullname" . }}-db
  selector:
    {{- include "elisa_db.selectorLabels" . | nindent 4 }}
